### ISSUE TITLE
Config changes not getting reflected when using custom config .yaml filr

### ISSUE THREAD

**Issue by sohamtiwari3120** [s3prl/s3prl#189]
Hi @andi611,
I have been trying to load the `spectrogram` extractor, using the following custom config.
```
kaldi:
  feat_type: spectrogram
  spectrogram:
    frame_length: 1024.0
    frame_shift: 320.0

delta:
  order: 0
  win_length: 1024

cmvn:
  use_cmvn: False
```
And loading the extractor using the following statement:
```
torch.hub.load('s3prl/s3prl', self.s3prl_feature_type, config='./pytorch/s3prl_spectrogram.yaml').to('cuda')
```

However, the output spectrogram shape does not change even after using different frame lengths.
Using the default config on pytorch:
```
torch.Size([1, 1198, 257])
```

And using the custom config yaml file, I still get:
```
torch.Size([1, 1198, 257])
```

Can you please help me out with the same?

Sincerely,
Soham Tiwari
