### ISSUE TITLE
Keyword spotting task architecture in TERA paper

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#194]
Dear researcher, I'm wondering what is the exact classifier architecture in tera paper, the only information is it has two hidden layer, but I'm not very sure what is the exact number of hidden unit. Besides, is this architecture implemented in downstream/speech_commands/model.py?

**Comment by andi611** [comment]
Here is the link to one of my training log of the Keyword Spotting task: [google drive](https://drive.google.com/drive/folders/1W7RhEsvWMK0Lc4P2c4WoMGZSk6a7WaJF?usp=sharing)

The config I used was:
```yaml
runner:
  total_steps: 50000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 100
  eval_step: 1000
  save_step: 1000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 1400

downstream_expert:
  datarc:
    speech_commands_root: /work/a129195789/corpora/speech_commands_v0.01
    speech_commands_test_root: /work/a129195789/corpora/speech_commands_test_set_v0.01
    num_workers: 8
    batch_size: 32

  modelrc:
    hidden_dim: 256
```

And the model:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
    def __init__(self, input_dim, output_class_num, **kwargs):
        super(Model, self).__init__()
        hidden_dim = kwargs["hidden_dim"]
        self.connector = nn.Linear(input_dim, hidden_dim)
        self.fc1 = nn.Linear(hidden_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_class_num)

    def forward(self, features):
        features = F.relu(self.connector(features))
        features = self.fc1(features)
        pooled = features.mean(dim=1)
        predicted = self.fc2(pooled)
        return predicted
```

which I believe is identical to the one we have on master, thus you can run this task with `-d speech_commands`.
