### ISSUE TITLE
Help: Logmel spectrogram from s3prl 'mel'  slightly different from the one in librosa

### ISSUE THREAD

**Issue by sohamtiwari3120** [s3prl/s3prl#204]
Hi @andi611 @leo19941227 
For a particular audio file, I generated the logmel spectrograms using both s3prl and librosa. However, the spectrograms generated are slightly different. The differences are subtle - like the one from librosa has higher resolution than the one from s3prl. Can you help me on how to make the logmel spectrogram from s3prl **_exactly similar_** to that in librosa? What am I doing wrong?

Below is the image of the logmel spectrogram generated using librosa:
<a href="https://ibb.co/xzSmLQY"><img src="https://i.ibb.co/6DRvw58/spec-librosa.png" alt="spec-librosa" border="0"></a>

And below is the image of the logmel spectrogram using default 'mel' in s3prl
<a href="https://ibb.co/zFWBzgn"><img src="https://i.ibb.co/ZSRF0rL/spec-s3prl-2.png" alt="spec-s3prl-2" border="0"></a>

Here is the default 'mel' s3prl .yaml file used for reference:
```
win_ms: 25
hop_ms: 10
n_freq: 201
n_mels: 80
n_mfcc: 13

input:
  feat_type: mel # feat_type can be: wav, complx, linear, mel, mfcc, phase
  channel: 0
  log: True
  delta: 0
  cmvn: True
```

I tried changing the parameters of the librosa melspectrogram function to match the parameters used above for s3prl 'mel':
```
y, sr = librosa.load(librosa.ex('trumpet'))
mel_lib = librosa.feature.melspectrogram(y=y, sr=sr, n_mels = 80, n_fft=400, 
                                         hop_length=160, win_length=400, 
                               window='hann', center=True, pad_mode='reflect', 
                                         power=2.0)
```
