### ISSUE TITLE
The training time of pretrain models

### ISSUE THREAD

**Issue by leijue222** [s3prl/s3prl#359]
Pretrain upstream models, including Mockingjay, Audio ALBERT and TERA.
**How many** GPUs and **what types** of GPUs did these three models use, and **how long** did they train?

**Comment by leijue222** [comment]
I tried to start the TERA training, adjusted the bs, and used 8*P40(24G) graphics cards. After three days, the training progress was only 3%.
Here is my adjusted config file:
```
runner:
  n_epochs: -1
  total_steps: 1000000
  gradient_clipping: 5.0
  gradient_accumulate_steps: 8

  log_step: 50000
  save_step: 50000
  max_keep: 5

  fp16: false

optimizer:
  name: AdamW_with_schedule
  lr: 2.e-4
  warmup_proportion: 0.07

pretrain_expert:
  datarc:
    num_workers: 8
    train_batch_size: 128
    max_timestep: -200 # Max length for audio feature (0 for no restriction, negative value to set minimum timestep)
    libri_root: 'datasets/LibriSpeech/' # If raw libri data is provided, use on-the-fly feature extraction, else use the pre-extracted features under `file_path`
    file_path: 'data/len_for_bucket' # Pre-extracted features path. When using on-the-fly feature extraction, this is used to provide length for bucketing.
    sets: ['train-clean-100'] # can be the subset of ['train-clean-100', 'train-clean-360', 'train-other-500']
```
