### ISSUE TITLE
s3prl upstream key issue with local checkpoint

### ISSUE THREAD

**Issue by bloodraven66** [s3prl/s3prl#457]
# Bug report

**Describe the bug**
I'm not sure if this is a bug or if I'm missing something. I am using a custom wav2vec2 checkpoint as espnet frontend. s3prl does not load the keys by default.

This is with the latest espnet and s3prl (0.4.10). The relevant espnet config is shown below

```
frontend: s3prl
frontend_conf:  
    frontend_conf:
        upstream: wav2vec2_custom
        path_or_url: path_to_chk.pt  #(from https://github.com/AI4Bharat/IndicWav2Vec)
    multilayer_feature: True
```

This stop in ```load_converted_model``` function in ```s3prl/upstream/wav2vec2/convert.py```

The checkpoint has the following keys -
['args', 'cfg', 'model', 'criterion', 'optimizer_history', 'task_state', 'extra_state', 'last_optimizer_state']

and 'cfg' has the follwing keys - 
['_name', 'common', 'common_eval', 'distributed_training', 'dataset', 'optimization', 'checkpoint', 'bmuf', 'generation', 'eval_lm', 'interactive', 'model', 'task', 'criterion', 'optimizer', 'lr_scheduler', 'scoring', 'bpe', 'tokenizer', 'job_logging_cfg']

["task_cfg", "model_cfg", "model_weight"] keys are not present as required in ```load_converted_model```.
Currently, it runs with a workaround-
```
ckpt_state = torch.load(ckpt, map_location="cpu")

ckpt_state = {'task_cfg':ckpt_state["cfg"]["task"],
            'model_cfg':ckpt_state["cfg"]["model"],
            'model_weight':ckpt_state["model"]}
```

Did I miss an existing functionality where the keys are converted directly? I see that the ```UpstreamExpert``` in ```s3prl/upstream/wav2vec2/expert.py``` uses only ```load_converted_model``` and not ```load_and_convert_fairseq_ckpt```
